name: Build and Deploy Ping-Pong App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes an image named 'kylmps/pingpong' to align with manifests
      - name: Build and Push Docker Image
        run: |
          docker build -t kylmps/pingpong:${{ github.sha }} .
          docker push kylmps/pingpong:${{ github.sha }}

      - name: Checkout Configuration Repo
        uses: actions/checkout@v4
        with:
          repository: kylemaps/log-pong-config
          path: log-pong-config
          token: ${{ secrets.GH_PAT_90_D }} # Use the PAT here

      - name: Setup Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      # Uses kustomize to safely update the image tag in the config repo
      - name: Update Image Tag
        run: |
          cd log-pong-config
          kustomize edit set image kylmps/pingpong=kylmps/pingpong:${{ github.sha }}

      - name: Commit and Push Changes
        run: |
          cd log-pong-config
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update image for pingpong-app to ${{ github.sha }}" || echo "No changes to commit"
          git push
